version: "3.7"

services:

  plex:
    container_name: app-plex
    image: jaymoulin/plex:1.30.1.6562
    expose:
      - 32400
      - 33400
    # Descomentar si NO usas network_mode: "host"
    # ports:
    #  - 32400:32400
    #  - 33400:33400
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Lima
    volumes:
      - ${STORAGE}/piserver/plex:/root/Library/Application Support/Plex Media Server
      - ${STORAGE}/media:/media
      - ${STORAGE}/piserver/tmp:/tmp
    restart: always
    network_mode: "host" # Solo funciona en Linux

  transmission:
    container_name: app-transmission
    image : jaymoulin/transmission:3.00-1.6.1
    command: transmission-daemon -f -g /config
    volumes:
      - ./transmission:/config
      - ${STORAGE}/downloads/torrents:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    expose:
      - 9091
    restart: unless-stopped
